# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 14:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appraisal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('year', models.CharField(max_length=4)),
                ('score', models.IntegerField()),
                ('is_approved', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Competencies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('score', models.IntegerField()),
                ('appraisal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appraisal.Appraisal')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('type', models.CharField(choices=[('mg', 'Manager'), ('gm', 'General Manager'), ('sf', 'Staff')], default='Staff', max_length=2)),
                ('joined_date', models.DateTimeField(verbose_name='date joined')),
                ('is_active', models.BooleanField()),
                ('reporting_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appraisal.Employee')),
            ],
        ),
        migrations.AddField(
            model_name='appraisal',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appraisal.Employee'),
        ),
    ]
