# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appraisal',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='competencies',
            name='appraisal',
        ),
        migrations.AddField(
            model_name='competencies',
            name='appraisal',
            field=models.ManyToManyField(to='appraisal.Appraisal'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
