# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0002_auto_20170906_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='joined_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date joined'),
        ),
    ]
