# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 07:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0003_auto_20170906_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='reporting_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appraisal.Employee'),
        ),
    ]
