# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 18:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0005_employee_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appraisal',
            name='employee',
        ),
        migrations.AddField(
            model_name='appraisal',
            name='from_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='giver', to='appraisal.Employee'),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='to_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='appraisal.Employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='type',
            field=models.CharField(choices=[('mg', 'Manager'), ('gm', 'General Manager'), ('sf', 'Staff')], default='sf', max_length=2),
        ),
    ]
