# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 14:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0006_auto_20170911_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competencies',
            name='appraisal',
        ),
        migrations.AddField(
            model_name='competencies',
            name='appraisal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='giver', to='appraisal.Appraisal'),
        ),
        migrations.AlterField(
            model_name='competencies',
            name='name',
            field=models.CharField(choices=[('py', 'Python'), ('tw', 'Team Work'), ('dj', 'Django'), ('cm', 'Communication')], max_length=35),
        ),
    ]
