# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0007_auto_20170917_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appraisal',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
