# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 17:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0008_auto_20170917_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competencies',
            name='appraisal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appraisal.Appraisal'),
        ),
    ]
